# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'XRPTipBot' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread    
  ]

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
 
  # Third party deps podspec link

  # firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'

  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'RNDiscovery', path: '../node_modules/react-native-discovery'
  pod 'Interactable', :path => '../node_modules/react-native-interactable'
  pod 'RNViewShot', path: '../node_modules/react-native-view-shot'
  pod 'RNShare', path: '../node_modules/react-native-share'
  pod 'RNDeviceInfo', path: '../node_modules/react-native-device-info'
  pod 'BVLinearGradient', path: '../node_modules/react-native-linear-gradient'
  pod 'lottie-react-native', path: '../node_modules/lottie-react-native'

end
