# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'XRPTipBot' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
 
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'

end
